[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
rand = "0.8"

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "field_bench"
harness = false
path = "benches/field_bench.rs"